# Generated by Django 2.0.3 on 2018-04-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20180416_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudadNacimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad_nacimiento', to='asistencia.Ciudad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudadResidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad_residencia', to='asistencia.Ciudad'),
        ),
    ]
