# Generated by Django 2.0.3 on 2018-04-30 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_auto_20180423_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.Tipo'),
        ),
    ]
