# Generated by Django 2.0.3 on 2018-05-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistencia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numeroDocumento', models.BigIntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Entidad')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Ocupacion')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.TipoDocumento')),
            ],
        ),
    ]
