# Generated by Django 2.0.3 on 2018-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.FileField(upload_to='static/archivos/')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
